package projetodeaplicacao;

import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import org.jrimum.bopepo.BancosSuportados;
import org.jrimum.bopepo.Boleto;
import static org.jrimum.bopepo.exemplo.Exemplos.mostreBoletoNaTela;
import org.jrimum.bopepo.view.BoletoViewer;
import org.jrimum.domkee.comum.pessoa.endereco.CEP;
import org.jrimum.domkee.comum.pessoa.endereco.Endereco;
import org.jrimum.domkee.comum.pessoa.endereco.UnidadeFederativa;
import org.jrimum.domkee.financeiro.banco.febraban.Agencia;
import org.jrimum.domkee.financeiro.banco.febraban.Carteira;
import org.jrimum.domkee.financeiro.banco.febraban.Cedente;
import org.jrimum.domkee.financeiro.banco.febraban.ContaBancaria;
import org.jrimum.domkee.financeiro.banco.febraban.NumeroDaConta;
import org.jrimum.domkee.financeiro.banco.febraban.Sacado;
import org.jrimum.domkee.financeiro.banco.febraban.SacadorAvalista;
import org.jrimum.domkee.financeiro.banco.febraban.TipoDeTitulo;
import org.jrimum.domkee.financeiro.banco.febraban.Titulo;
//import org.jrimum.domkee.financeiro.banco.febraban.Titulo.Aceite;


public class MainView extends javax.swing.JFrame {
    
    CedenteView CedenteView = new CedenteView();
    ContaBancariaView ContaBancariaView = new ContaBancariaView();
    SacadoAvalistaView SacadoAvalistaView = new SacadoAvalistaView();
    SacadoView SacadoView = new SacadoView();
    TituloView TituloView = new TituloView();
    BoletoView BoletoView = new BoletoView();
    
    
    
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeradorDeBoletoLabel = new javax.swing.JLabel();
        CedenteViewBotao = new javax.swing.JToggleButton();
        Sacado = new javax.swing.JToggleButton();
        SacadoAvalista = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        ContaBancariaBotao = new javax.swing.JToggleButton();
        Titulo = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de boletos bancários");
        setBackground(new java.awt.Color(254, 254, 254));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        GeradorDeBoletoLabel.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        GeradorDeBoletoLabel.setForeground(new java.awt.Color(1, 1, 1));
        GeradorDeBoletoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetodeaplicacao/Icon.png"))); // NOI18N
        GeradorDeBoletoLabel.setText("GERADOR DE BOLETOS BANCÁRIOS");

        CedenteViewBotao.setText("Cedente");
        CedenteViewBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedenteViewBotaoActionPerformed(evt);
            }
        });

        Sacado.setText("Sacado");
        Sacado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SacadoActionPerformed(evt);
            }
        });

        SacadoAvalista.setText("Sacado avalista");
        SacadoAvalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SacadoAvalistaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 2, 2));
        jLabel1.setText("Cadastrar dados");

        ContaBancariaBotao.setText("Conta bancária");
        ContaBancariaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContaBancariaBotaoActionPerformed(evt);
            }
        });

        Titulo.setText("Título");
        Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloActionPerformed(evt);
            }
        });

        jToggleButton5.setText("Boleto");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Gerar boleto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GeradorDeBoletoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ContaBancariaBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Sacado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SacadoAvalista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CedenteViewBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(GeradorDeBoletoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(CedenteViewBotao)
                .addGap(6, 6, 6)
                .addComponent(Sacado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SacadoAvalista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContaBancariaBotao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton5)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CedenteViewBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedenteViewBotaoActionPerformed
         
        CedenteView.setVisible(true); 
        CedenteView.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        CedenteView.setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());


       
    }//GEN-LAST:event_CedenteViewBotaoActionPerformed

    private void ContaBancariaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContaBancariaBotaoActionPerformed
       
         ContaBancariaView.setVisible(true);
         ContaBancariaView.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         ContaBancariaView.setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());

        
    }//GEN-LAST:event_ContaBancariaBotaoActionPerformed

    private void SacadoAvalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SacadoAvalistaActionPerformed
        
        
        SacadoAvalistaView.setVisible(true);
        SacadoAvalistaView.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        SacadoAvalistaView.setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());
        
        
        
    }//GEN-LAST:event_SacadoAvalistaActionPerformed

    private void TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloActionPerformed
        
        TituloView.setVisible(true);
        TituloView.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        TituloView.setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());
        
    }//GEN-LAST:event_TituloActionPerformed

    private void SacadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SacadoActionPerformed
        
        SacadoView.setVisible(true);
        SacadoView.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        SacadoView.setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());
    }//GEN-LAST:event_SacadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{
        
        Cedente cedente = new Cedente(CedenteView.NomeCedente, CedenteView.CNPJCedente);
        
        Sacado sacado = new Sacado(SacadoView.Nome, SacadoView.CPF);

        // Informando o endereço do sacado.
        Endereco enderecoSac = new Endereco();
        switch (SacadoView.UF){
        
            case "AC": enderecoSac.setUF(UnidadeFederativa.AC); 
            break;
            case "AL": enderecoSac.setUF(UnidadeFederativa.AL);
            break;
            case "AP": enderecoSac.setUF(UnidadeFederativa.AP);
            break;
            case "AM": enderecoSac.setUF(UnidadeFederativa.AM); 
            break;  
            case "BA": enderecoSac.setUF(UnidadeFederativa.BA);
            break;
            case "CE": enderecoSac.setUF(UnidadeFederativa.CE); 
            break;
            case "DF": enderecoSac.setUF(UnidadeFederativa.DF);
            break;
            case "ES": enderecoSac.setUF(UnidadeFederativa.ES); 
            break;
            case "GO": enderecoSac.setUF(UnidadeFederativa.GO);
            break;
            case "MT": enderecoSac.setUF(UnidadeFederativa.MT); 
            break;
            case "MS": enderecoSac.setUF(UnidadeFederativa.MS); 
            break;
            case "MG": enderecoSac.setUF(UnidadeFederativa.MG); 
            break;
            case "PA": enderecoSac.setUF(UnidadeFederativa.PA); 
            break;
            case "PB": enderecoSac.setUF(UnidadeFederativa.PB); 
            break;            
            case "PR": enderecoSac.setUF(UnidadeFederativa.PR); 
            break;
            case "PE": enderecoSac.setUF(UnidadeFederativa.PE); 
            break;
            case "PI": enderecoSac.setUF(UnidadeFederativa.PI); 
            break;
            case "RJ": enderecoSac.setUF(UnidadeFederativa.RJ); 
            break;
            case "RN": enderecoSac.setUF(UnidadeFederativa.RN); 
            break;
            case "RS": enderecoSac.setUF(UnidadeFederativa.RS); 
            break;
            case "RO": enderecoSac.setUF(UnidadeFederativa.RO); 
            break;
            case "RR": enderecoSac.setUF(UnidadeFederativa.RR); 
            break;
            case "SC": enderecoSac.setUF(UnidadeFederativa.SC); 
            break;
            case "SP": enderecoSac.setUF(UnidadeFederativa.SP); 
            break;
            case "SE": enderecoSac.setUF(UnidadeFederativa.SE);
            break;
            case "TO": enderecoSac.setUF(UnidadeFederativa.TO);
            break;

        }
        
        enderecoSac.setLocalidade(SacadoView.Localidade);
        enderecoSac.setCep(new CEP(SacadoView.CEP));
        enderecoSac.setBairro(SacadoView.Bairro);
        enderecoSac.setLogradouro(SacadoView.Logradouro);
        enderecoSac.setNumero(SacadoView.Numero);
        sacado.addEndereco(enderecoSac);
        
        SacadorAvalista sacadorAvalista = new SacadorAvalista(SacadoAvalistaView.Nome, SacadoAvalistaView.CPF);
        
        Endereco enderecoSacAval = new Endereco();
        switch (SacadoView.UF){
        
            case "AC": enderecoSacAval.setUF(UnidadeFederativa.AC); 
            break;
            case "AL": enderecoSacAval.setUF(UnidadeFederativa.AL);
            break;
            case "AP": enderecoSacAval.setUF(UnidadeFederativa.AP);
            break;
            case "AM": enderecoSacAval.setUF(UnidadeFederativa.AM); 
            break;  
            case "BA": enderecoSacAval.setUF(UnidadeFederativa.BA);
            break;
            case "CE": enderecoSacAval.setUF(UnidadeFederativa.CE); 
            break;
            case "DF": enderecoSacAval.setUF(UnidadeFederativa.DF);
            break;
            case "ES": enderecoSacAval.setUF(UnidadeFederativa.ES); 
            break;
            case "GO": enderecoSacAval.setUF(UnidadeFederativa.GO);
            break;
            case "MT": enderecoSacAval.setUF(UnidadeFederativa.MT); 
            break;
            case "MS": enderecoSacAval.setUF(UnidadeFederativa.MS); 
            break;
            case "MG": enderecoSacAval.setUF(UnidadeFederativa.MG); 
            break;
            case "PA": enderecoSacAval.setUF(UnidadeFederativa.PA); 
            break;
            case "PB": enderecoSacAval.setUF(UnidadeFederativa.PB); 
            break;            
            case "PR": enderecoSacAval.setUF(UnidadeFederativa.PR); 
            break;
            case "PE": enderecoSacAval.setUF(UnidadeFederativa.PE); 
            break;
            case "PI": enderecoSacAval.setUF(UnidadeFederativa.PI); 
            break;
            case "RJ": enderecoSacAval.setUF(UnidadeFederativa.RJ); 
            break;
            case "RN": enderecoSacAval.setUF(UnidadeFederativa.RN); 
            break;
            case "RS": enderecoSacAval.setUF(UnidadeFederativa.RS); 
            break;
            case "RO": enderecoSacAval.setUF(UnidadeFederativa.RO); 
            break;
            case "RR": enderecoSacAval.setUF(UnidadeFederativa.RR); 
            break;
            case "SC": enderecoSacAval.setUF(UnidadeFederativa.SC); 
            break;
            case "SP": enderecoSacAval.setUF(UnidadeFederativa.SP); 
            break;
            case "SE": enderecoSacAval.setUF(UnidadeFederativa.SE);
            break;
            case "TO": enderecoSacAval.setUF(UnidadeFederativa.TO);
            break;

        }
        
        enderecoSacAval.setLocalidade(SacadoAvalistaView.Localidade);
        enderecoSacAval.setCep(new CEP(SacadoAvalistaView.CEP));
        enderecoSacAval.setBairro(SacadoAvalistaView.Bairro);
        enderecoSacAval.setLogradouro(SacadoAvalistaView.Logradouro);
        enderecoSacAval.setNumero(SacadoAvalistaView.Numero);
        sacadorAvalista.addEndereco(enderecoSacAval);
        
        ContaBancaria contaBancaria = new ContaBancaria(BancosSuportados.BANCO_BRADESCO.create());
        int NumConta = Integer.parseInt(ContaBancariaView.NumeroConta);
        contaBancaria.setNumeroDaConta(new NumeroDaConta(NumConta, "0"));
        int TipoCarteira = Integer.parseInt(ContaBancariaView.TipoCarteira);
        contaBancaria.setCarteira(new Carteira(TipoCarteira));
        int NumAgencia = Integer.parseInt(ContaBancariaView.NumeroAgencia);
        contaBancaria.setAgencia(new Agencia(NumAgencia, "1"));
        
        Titulo titulo = new Titulo(contaBancaria, sacado, cedente, sacadorAvalista);
        titulo.setNumeroDoDocumento(TituloView.NumeroDocumento);
        titulo.setNossoNumero(TituloView.NossoNumero);
        titulo.setDigitoDoNossoNumero(TituloView.DigitoNossoNumero);
        titulo.setValor(new BigDecimal(TituloView.Valor));
        titulo.setDataDoDocumento(new Date());
        titulo.setDataDoVencimento(new Date());
        
        switch (TituloView.Tipo){
            
            case "CH":titulo.setTipoDeDocumento(TipoDeTitulo.CH_CHEQUE);
            break;
            case "DM":titulo.setTipoDeDocumento(TipoDeTitulo.DM_DUPLICATA_MERCANTIL);
            break;
            case "DMI":titulo.setTipoDeDocumento(TipoDeTitulo.DMI_DUPLICATA_MERCANTIL_PARA_INDICACAO);
            break;
            case "DS":titulo.setTipoDeDocumento(TipoDeTitulo.DS_DUPLICATA_DE_SERVICO);
            break;
            case "DSI":titulo.setTipoDeDocumento(TipoDeTitulo.DSI_DUPLICATA_DE_SERVICO_PARA_INDICACAO);
            break;
            case "DR":titulo.setTipoDeDocumento(TipoDeTitulo.DR_DUPLICATA_RURAL);
            break;
            case "LC":titulo.setTipoDeDocumento(TipoDeTitulo.LC_LETRA_DE_CAMBIO);
            break;
            case "NCC":titulo.setTipoDeDocumento(TipoDeTitulo.NCC_NOTA_DE_CREDITO_COMERCIAL);
            break;
            case "NCE":titulo.setTipoDeDocumento(TipoDeTitulo.NCE_NOTA_DE_CREDITO_A_EXPORTACAO);
            break;
            case "NCI":titulo.setTipoDeDocumento(TipoDeTitulo.NCI_NOTA_DE_CREDITO_INDUSTRIAL);
            break;
            case "NCR":titulo.setTipoDeDocumento(TipoDeTitulo.NCR_NOTA_DE_CREDITO_RURAL);
            break;
            case "NP":titulo.setTipoDeDocumento(TipoDeTitulo.NP_NOTA_PROMISSORIA);
            break;
            case "NPR":titulo.setTipoDeDocumento(TipoDeTitulo.NPR_NOTA_PROMISSORIA_RURAL);
            break;
            case "TM":titulo.setTipoDeDocumento(TipoDeTitulo.TM_TRIPLICATA_MERCANTIL);
            break;
            case "TS":titulo.setTipoDeDocumento(TipoDeTitulo.TS_TRIPLICATA_DE_SERVICO);
            break;
            case "RC":titulo.setTipoDeDocumento(TipoDeTitulo.RC_RECIBO);
            break;
            case "FAT":titulo.setTipoDeDocumento(TipoDeTitulo.FAT_FATURA);
            break;
            case "ND":titulo.setTipoDeDocumento(TipoDeTitulo.ND_NOTA_DE_DEBITO);
            break;
            case "AP":titulo.setTipoDeDocumento(TipoDeTitulo.AP_APOLICE_DE_SEGURO);
            break;
            case "ME":titulo.setTipoDeDocumento(TipoDeTitulo.ME_MENSALIDADE_ESCOLAR);
            break;
            case "PC":titulo.setTipoDeDocumento(TipoDeTitulo.PC_PARCELA_DE_CONSORCIO);
            break;
            case "NF":titulo.setTipoDeDocumento(TipoDeTitulo.DD_DOCUMENTO_DE_DIVIDA);
            break;
            case "DD":titulo.setTipoDeDocumento(TipoDeTitulo.NF_NOTA_FISCAL);
            break;
            case "CPR":titulo.setTipoDeDocumento(TipoDeTitulo.CEDULA_DE_PRODUTO_RURAL);
            break;
            case "DAE":titulo.setTipoDeDocumento(TipoDeTitulo.DIVIDA_ATIVA_DE_ESTADO);
            break;
            case "DAM":titulo.setTipoDeDocumento(TipoDeTitulo.DIVIDA_ATIVA_DE_MUNICIPIO);
            break;
            case "DAU":titulo.setTipoDeDocumento(TipoDeTitulo.DIVIDA_ATIVA_DA_UNIAO);   
            break;
            case "CC":titulo.setTipoDeDocumento(TipoDeTitulo.COTA_CONDOMINIAL);
            break;
            case "OT":titulo.setTipoDeDocumento(TipoDeTitulo.OUTROS);
            break;
            
        }
        //titulo.setAceite(Aceite.A);
        titulo.setDesconto(new BigDecimal(TituloView.Desconto));
        titulo.setDeducao(BigDecimal.ZERO);
        titulo.setMora(BigDecimal.ZERO);
        titulo.setAcrecimo(BigDecimal.ZERO);
        titulo.setValorCobrado(BigDecimal.ZERO);
        
        Boleto boleto = new Boleto(titulo);
                
        boleto.setLocalPagamento(BoletoView.LocalPagamento);
        boleto.setInstrucaoAoSacado(BoletoView.InstrucaoSacado);
        boleto.setInstrucao1(BoletoView.Instrucao1);
        boleto.setInstrucao2(BoletoView.Instrucao2);
        boleto.setInstrucao3(BoletoView.Instrucao3);
        boleto.setInstrucao4(BoletoView.Instrucao4);
        boleto.setInstrucao5(BoletoView.Instrucao5);
        boleto.setInstrucao6(BoletoView.Instrucao6);
        boleto.setInstrucao7(BoletoView.Instrucao7);
        boleto.setInstrucao8(BoletoView.Instrucao8);   
        
        BoletoViewer boletoViewer = new BoletoViewer(boleto);

        File arquivoPdf = boletoViewer.getPdfAsFile("MeuPrimeiroBoleto.pdf");
        
        mostreBoletoNaTela(arquivoPdf);
        
        }
        
        catch(IllegalArgumentException e){
            
            JOptionPane.showMessageDialog(null, "Existem campos não preenchidos", "Erro", JOptionPane.ERROR_MESSAGE);
            
            
        }
        

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        this.setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        
        
        BoletoView.setVisible(true);
        BoletoView.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        BoletoView.setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());
        
        
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CedenteViewBotao;
    private javax.swing.JToggleButton ContaBancariaBotao;
    private javax.swing.JLabel GeradorDeBoletoLabel;
    private javax.swing.JToggleButton Sacado;
    private javax.swing.JToggleButton SacadoAvalista;
    private javax.swing.JToggleButton Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton5;
    // End of variables declaration//GEN-END:variables
}
